version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIGTREE_APP_TIMEZONE: ${BIGTREE_APP_TIMEZONE:-Asia/Seoul}
    image: ${COMPOSE_PROJECT_NAME:-ko_bigbird}_2.4.0-gpu
    command: /app/ko_bigbird/bigbird/pretrain/run_pretraining.sh
    volumes:
      - type: volume
        source: vol
        target: /app